### ISSUE TITLE
Comentarios sobre el ejercicio

### ISSUE THREAD

**Issue by m4n50n** [Manuquim/proyecto1bis#1]
Hola Manuel,

✔ Muy bien el ejercicio en general. El resultado es prácticamente el que se pide. No obstante, te rechazo el ejercicio debido a algunos fallos que he visto:

- Los comentarios en CSS se ponen entre _/*_ y _*/_ y no con _//_ como en HTML. Cada lenguaje tiene su propia nomenclatura de comentarios. Esto:
![image](https://user-images.githubusercontent.com/92524023/201068266-a5a8e962-8f9c-46c4-835a-fab5e39ad4ea.png)

Sería esto:
![image](https://user-images.githubusercontent.com/92524023/201068322-8e2f0f63-32c1-41e6-a04e-55c683a5bf2b.png)

Siempre que un comentario esté bien puesto, el editor lo marcará en verde, así que puedes guiarte por ahí.

- La propiedad size no existe en CSS. La tienes en la línea 53 de `styles.css`. Si usas el inspector de Chrome, ya te dice que no se aplica:
![image](https://user-images.githubusercontent.com/92524023/201068842-05610d0c-d435-4f09-8635-e43b21f81371.png)

- En CSS, en las propiedades cuyo valor se corresponde con un tamaño (margin, padding, etc...), este debe usar una unidad de medida obligatoriamente, ya sea px, porcentajes, em o rem. Puedes leer más aquí: https://franciscoamk.com/unidades-de-medida-en-css/

Te lo comento porque en la línea 62 de `styles.css`: 
![image](https://user-images.githubusercontent.com/92524023/201069475-6b8ffa78-d788-4da6-8100-696db35d7aa6.png)

A ese padding se le debe poner una unidad, ya que de ahora mismo el navegador tampoco lo aplica:
![image](https://user-images.githubusercontent.com/92524023/201069523-abcadcd2-deb7-431d-9b8b-9d65a394e6d9.png)

- Podrías dar más padding a la postal en sí, así el título y el logo no quedarían tan pegados a los lados, o en su caso, dar más width a `.postcard`, ya que ahora mismo los inputs se desbordan:
![image](https://user-images.githubusercontent.com/92524023/201071496-f221113d-2099-4671-ac50-94356e7d75fd.png)

**Comment by Manuquim** [comment]
Ok , gracias por los comentarios. Los corrijo y reenvío. Saludos.
